name: project CI

on:
  push:
    path-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16', 'latest']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install --global pnpm grunt-cli
          pnpm install 
      - name: Run tests
        run: grunt test
